apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dejavu-core-data
  namespace: dejavu
  labels:
    app.kubernetes.io/name: dejavu-core
    app.kubernetes.io/part-of: dejavu
    app.kubernetes.io/managed-by: autopoc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
