apiVersion: v1
kind: Service
metadata:
  name: dejavu-core
  namespace: dejavu
  labels:
    app.kubernetes.io/name: dejavu-core
    app.kubernetes.io/part-of: dejavu
    app.kubernetes.io/managed-by: autopoc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dejavu-core
  ports:
    - port: 8765
      targetPort: 8765
      protocol: TCP
      name: http
